import React from "react";
import { FaHeartbeat, FaMapMarkerAlt } from "react-icons/fa";
export const causesData = [
    {
      id: 1,
      imageSrc: "/images/cancerFoundation.png",
      altText: "Cancer foundation",
      profileImageSrc: "/images/cancerEllipse.svg",
      title: "Cancer foundation",
      daysLeft: "15 days left",
      progressPercentage: 85,
      donationAmount: 1700000,
      goalAmount: 2000000,
      description: "This cause is for Ikemefuna, a Nigerian boy that needs surgery for his cancer and is seeking your funding for the sum of 100m more...",
      tags: [
        { icon: React.createElement(FaHeartbeat, { className: "mr-1" }), text: "Healthcare" },
        { icon: React.createElement(FaMapMarkerAlt, { className: "mr-1" }), text: "Abuja, Nigeria" },
      ],
    },
    {
      id: 2,
      imageSrc: "/images/flood1.png",
      altText: "Maiduguri flood",
      profileImageSrc: "/images/maiduguriEllipse1.png",
      title: "Maiduguri flood",
      daysLeft: "15 days left",
      progressPercentage: 65,
      donationAmount: 1300000,
      goalAmount: 2000000,
      tags: [
        { icon: React.createElement(FaHeartbeat, { className: "mr-1" }), text: "Disaster Relief" },
        { icon: React.createElement(FaMapMarkerAlt, { className: "mr-1" }), text: "Maiduguri, Nigeria" },
      ],
    },
    {
      id: 3,
      imageSrc: "/images/flood1.png",
      altText: "Maiduguri flood",
      profileImageSrc: "/images/maiduguriEllipse1.png",
      title: "Maiduguri flood",
      daysLeft: "15 days left",
      progressPercentage: 65,
      donationAmount: 1300000,
      goalAmount: 2000000,
      tags: [
        { icon: React.createElement(FaHeartbeat, { className: "mr-1" }), text: "Disaster Relief" },
        { icon: React.createElement(FaMapMarkerAlt, { className: "mr-1" }), text: "Maiduguri, Nigeria" },
      ],
    },
    {
      id: 4,
      imageSrc: "/images/flood1.png",
      altText: "Maiduguri flood",
      profileImageSrc: "/images/maiduguriEllipse1.png",
      title: "Maiduguri flood",
      daysLeft: "15 days left",
      progressPercentage: 65,
      donationAmount: 1300000,
      goalAmount: 2000000,
      tags: [
        { icon: React.createElement(FaHeartbeat, { className: "mr-1" }), text: "Disaster Relief" },
        { icon: React.createElement(FaMapMarkerAlt, { className: "mr-1" }), text: "Maiduguri, Nigeria" },
      ],
    },
    {
      id: 5,
      imageSrc: "/images/flood1.png",
      altText: "Maiduguri flood",
      profileImageSrc: "/images/maiduguriEllipse1.png",
      title: "Maiduguri flood",
      daysLeft: "15 days left",
      progressPercentage: 65,
      donationAmount: 1300000,
      goalAmount: 2000000,
      tags: [
        { icon: React.createElement(FaHeartbeat, { className: "mr-1" }), text: "Disaster Relief" },
        { icon: React.createElement(FaMapMarkerAlt, { className: "mr-1" }), text: "Maiduguri, Nigeria" },
      ],
    },
    {
      id: 6,
      imageSrc: "/images/flood1.png",
      altText: "Maiduguri flood",
      profileImageSrc: "/images/maiduguriEllipse1.png",
      title: "Maiduguri flood",
      daysLeft: "15 days left",
      progressPercentage: 65,
      donationAmount: 1300000,
      goalAmount: 2000000,
      tags: [
        { icon: React.createElement(FaHeartbeat, { className: "mr-1" }), text: "Disaster Relief" },
        { icon: React.createElement(FaMapMarkerAlt, { className: "mr-1" }), text: "Maiduguri, Nigeria" },
      ],
    },
    {
      id: 7,
      imageSrc: "/images/flood1.png",
      altText: "Maiduguri flood",
      profileImageSrc: "/images/maiduguriEllipse1.png",
      title: "Maiduguri flood",
      daysLeft: "15 days left",
      progressPercentage: 65,
      donationAmount: 1300000,
      goalAmount: 2000000,
      tags: [
        { icon: React.createElement(FaHeartbeat, { className: "mr-1" }), text: "Disaster Relief" },
        { icon: React.createElement(FaMapMarkerAlt, { className: "mr-1" }), text: "Maiduguri, Nigeria" },
      ],
    },
    {
      id: 8,
      imageSrc: "/images/flood1.png",
      altText: "Maiduguri flood",
      profileImageSrc: "/images/maiduguriEllipse1.png",
      title: "Maiduguri flood",
      daysLeft: "15 days left",
      progressPercentage: 65,
      donationAmount: 1300000,
      goalAmount: 2000000,
      tags: [
        { icon: React.createElement(FaHeartbeat, { className: "mr-1" }), text: "Disaster Relief" },
        { icon: React.createElement(FaMapMarkerAlt, { className: "mr-1" }), text: "Maiduguri, Nigeria" },
      ],
    },
    {
      id: 9,
      imageSrc: "/images/flood1.png",
      altText: "Maiduguri flood",
      profileImageSrc: "/images/maiduguriEllipse1.png",
      title: "Maiduguri flood",
      daysLeft: "15 days left",
      progressPercentage: 65,
      donationAmount: 1300000,
      goalAmount: 2000000,
      tags: [
        { icon: React.createElement(FaHeartbeat, { className: "mr-1" }), text: "Disaster Relief" },
        { icon: React.createElement(FaMapMarkerAlt, { className: "mr-1" }), text: "Maiduguri, Nigeria" },
      ],
    },
    // Add more causes here
  ];